{
 "title": "API Health",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(events_received_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Events Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(events_processed_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Events Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(events_failed_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Pipeline Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pipeline_seconds_sum[5m])/rate(pipeline_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P 95",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pipeline_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(clickhouse_insert_seconds_sum[5m])/rate(clickhouse_insert_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P 99",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(pipeline_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n0.95,\nsum(rate(clickhouse_insert_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(events_received_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(events_processed_total[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "rate(events_failed_total[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}